language: rust
cache: cargo
rust:
  - stable
  - nightly
env:
  # STM32L0x1, TSSOP14 package, 512 bytes flash, product category 1
  - FEATURES="rt mcu-STM32L011D3Px"
  # STM32L0x1, UFQFPN32 package, 1 KiB flash, product category 2
  - FEATURES="rt mcu-STM32L031K6Ux"
  # STM32L0x2, LQFP32 package, 2 KiB flash, product category 3, enable usbd
  - FEATURES="rt mcu-STM32L052K8Tx stm32-usbd"
  # STM32L0x3, TFBGA64 package, 6 KiB flash, product category 5, enable usbd
  - FEATURES="rt mcu-STM32L073RBHx stm32-usbd"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt
script:
  - RUSTFLAGS="-D warnings" cargo build --release --examples --features="$FEATURES"
  - cargo fmt --all -- --check
